import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";

export const generateResearchPDF = async (
    reportId: string,
    query: string,
    aiReport: string
) => {
    return new Promise<string>((resolve, reject) => {
        try {
            const fileName = `report-${reportId}.pdf`;

            const filePath = path.join(
                process.cwd(),
                "uploads",
                "reports",
                fileName
            );

            const doc = new PDFDocument({
                bufferPages: true,
                margins: {
                    top: 60,
                    bottom: 60,
                    left: 60,
                    right: 60,
                },
                size: "A4",
            });

            const stream = fs.createWriteStream(filePath);

            doc.pipe(stream);

            // =========================
            // STATIC FOOTER RENDERED AT THE END
            // =========================

            // =========================
            // COVER PAGE
            // =========================

            doc
                .rect(
                    0,
                    0,
                    doc.page.width,
                    220
                )
                .fill("#111827");

            doc
                .fillColor("white")
                .fontSize(30)
                .font("Helvetica-Bold")
                .text(
                    "AI Drug Repurposing",
                    60,
                    80,
                    {
                        align: "center",
                    }
                );

            doc
                .fontSize(30)
                .font("Helvetica-Bold")
                .text(
                    "Research Report",
                    {
                        align: "center",
                    }
                );

            doc
                .moveDown(4)
                .fillColor("#111111")
                .fontSize(18)
                .font("Helvetica-Bold")
                .text(
                    "Research Query",
                    {
                        align: "center",
                    }
                );

            doc
                .moveDown(0.5)
                .fontSize(24)
                .font("Helvetica")
                .fillColor("#2563EB")
                .text(query, {
                    align: "center",
                });

            doc.moveDown(3);

            doc
                .fontSize(12)
                .fillColor("#666666")
                .text(
                    `Generated on ${new Date().toLocaleString()}`,
                    {
                        align: "center",
                    }
                );

            doc.moveDown(20);

            doc
                .fontSize(14)
                .fillColor("#444444")
                .text(
                    "Generated by Agentic AI Research Assistant",
                    {
                        align: "center",
                    }
                );

            // =========================
            // TABLE OF CONTENTS
            // =========================

            doc.addPage();

            doc
                .fontSize(26)
                .font("Helvetica-Bold")
                .fillColor("#111111")
                .text(
                    "Table of Contents"
                );

            doc.moveDown(2);

            const tocItems = [
                "Executive Summary",
                "Disease Background",
                "Drug Overview",
                "Mechanism of Action",
                "Literature Review",
                "Clinical Insights",
                "Safety Analysis",
                "Market Potential",
                "Challenges",
                "Conclusion",
                "References",
            ];

            tocItems.forEach((item, index) => {
                doc
                    .fontSize(14)
                    .font("Helvetica")
                    .fillColor("#333333")
                    .text(
                        `${index + 1}. ${item}`,
                        {
                            lineGap: 8,
                        }
                    );
            });

            // =========================
            // MAIN CONTENT PAGE
            // =========================

            doc.addPage();

            // =========================
            // HELPERS
            // =========================

            const cleanInline = (
                text: string
            ) => {
                return text
                    .replace(
                        /__(.*?)__/g,
                        "$1"
                    )
                    .replace(
                        /\*\*(.*?)\*/g,
                        "$1"
                    )
                    .replace(
                        /_(.*?)_/g,
                        "$1"
                    )
                    .replace(
                        /`(.*?)`/g,
                        "$1"
                    )
                    .replace(
                        /#/g,
                        ""
                    );
            };

            const renderTextWithBold = (
                text: string,
                options: any = {}
            ) => {
                const parts = text.split(
                    /\*\*(.*?)\*\*/g
                );

                if (parts.length === 1) {
                    doc
                        .font(
                            options.font ||
                            "Helvetica"
                        )
                        .fillColor(
                            options.color ||
                            "#444444"
                        )
                        .text(
                            cleanInline(parts[0]),
                            options
                        );

                    return;
                }

                for (
                    let i = 0;
                    i < parts.length;
                    i++
                ) {
                    const isLast =
                        i === parts.length - 1;

                    const partText =
                        cleanInline(parts[i]);

                    if (i % 2 === 1) {
                        doc
                            .font(
                                "Helvetica-Bold"
                            )
                            .fillColor(
                                "#111111"
                            )
                            .text(partText, {
                                ...options,
                                continued:
                                    !isLast,
                            });
                    } else {
                        if (
                            partText ||
                            isLast
                        ) {
                            doc
                                .font(
                                    options.font ||
                                    "Helvetica"
                                )
                                .fillColor(
                                    options.color ||
                                    "#444444"
                                )
                                .text(partText, {
                                    ...options,
                                    continued:
                                        !isLast,
                                });
                        }
                    }
                }
            };

            // =========================
            // MAIN CONTENT
            // =========================

            const lines =
                aiReport.split("\n");

            for (let line of lines) {
                let trimmed = line.trim();

                if (!trimmed) {
                    doc.moveDown(0.7);
                    continue;
                }

                if (
                    trimmed.match(
                        /^[-_*]{3,}$/
                    )
                ) {
                    doc.moveDown(1);
                    continue;
                }

                // =========================
                // HEADINGS
                // =========================

                if (
                    trimmed.match(
                        /^#{1,6}\s/
                    )
                ) {
                    const level =
                        trimmed.match(
                            /^(#{1,6})\s/
                        )?.[1].length || 1;

                    const text =
                        cleanInline(
                            trimmed
                                .replace(
                                    /^#{1,6}\s+/,
                                    ""
                                )
                                .replace(
                                    /\*\*(.*?)\*\*/g,
                                    "$1"
                                )
                        );

                    if (level === 1) {
                        doc.moveDown(2);

                        const headingY = doc.y;

                        // Dark blue rounded style block
                        doc
                            .roundedRect(
                                50,
                                headingY,
                                495,
                                42,
                                8
                            )
                            .fill("#1E3A8A");

                        doc
                            .fillColor("#FFFFFF")
                            .fontSize(22)
                            .font("Helvetica-Bold")
                            .text(
                                text,
                                70,
                                headingY + 12
                            );

                        doc.moveDown(1.2);
                    } else {
                        doc.moveDown(1.5);

                        doc
                            .fontSize(16)
                            .font(
                                "Helvetica-Bold"
                            )
                            .fillColor(
                                "#1E3A8A"
                            )
                            .text(text);

                        doc.moveDown(0.8);
                    }
                }

                // =========================
                // BULLETS
                // =========================

                else if (
                    trimmed.match(
                        /^[-*+]\s/
                    )
                ) {
                    const text =
                        trimmed.replace(
                            /^[-*+]\s+/,
                            ""
                        );

                    doc.fontSize(12);

                    renderTextWithBold(
                        `• ${text}`,
                        {
                            lineGap: 8,
                            indent: 18,
                            font: "Helvetica",
                            color:
                                "#444444",
                        }
                    );
                }

                // =========================
                // NUMBERED LIST
                // =========================

                else if (
                    trimmed.match(
                        /^\d+\.\s/
                    )
                ) {
                    const num =
                        trimmed.match(
                            /^(\d+\.)\s/
                        )?.[1] || "";

                    const text =
                        trimmed.replace(
                            /^\d+\.\s+/,
                            ""
                        );

                    doc.fontSize(12);

                    renderTextWithBold(
                        `${num} ${text}`,
                        {
                            lineGap: 8,
                            indent: 18,
                            font: "Helvetica",
                            color:
                                "#444444",
                        }
                    );
                }

                // =========================
                // PARAGRAPHS
                // =========================
                else {

                    const lower = trimmed.toLowerCase();

                    const isHighlight =
                        lower.includes("key finding") ||
                        lower.includes("clinical insight") ||
                        lower.includes("market potential") ||
                        lower.includes("important") ||
                        lower.includes("safety warning");

                    // =========================
                    // HIGHLIGHT BOX
                    // =========================
                    if (isHighlight) {

                        const boxY = doc.y;

                        const boxHeight = 70;

                        // Background
                        doc
                            .roundedRect(
                                55,
                                boxY,
                                485,
                                boxHeight,
                                6
                            )
                            .fill("#EEF4FF");

                        // Left border
                        doc
                            .rect(
                                55,
                                boxY,
                                6,
                                boxHeight
                            )
                            .fill("#2563EB");

                        doc
                            .fillColor("#111827")
                            .fontSize(12);

                        doc.text(
                            trimmed,
                            75,
                            boxY + 15,
                            {
                                width: 440,
                                lineGap: 6,
                                align: "justify",
                            }
                        );

                        doc.moveDown(4);
                    }

                    // =========================
                    // NORMAL PARAGRAPH
                    // =========================
                    else {

                        doc.fontSize(12);

                        renderTextWithBold(
                            trimmed,
                            {
                                lineGap: 10,
                                font: "Helvetica",
                                color: "#374151",
                                align: "justify",
                            }
                        );

                        doc.moveDown(0.8);
                    }
                }
            } // Close the for (let line of lines) loop

            const range = doc.bufferedPageRange();
            for (let i = range.start; i < range.start + range.count; i++) {
                doc.switchToPage(i);

                doc
                    .fontSize(10)
                    .fillColor("#888888")
                    .text(
                        "Agentic AI Drug Repurposing System",
                        60,
                        doc.page.height - 40,
                        {
                            align: "left",
                            lineBreak: false,
                        }
                    );

                doc
                    .fontSize(10)
                    .fillColor("#888888")
                    .text(
                        `Page ${i + 1}`,
                        0,
                        doc.page.height - 40,
                        {
                            align: "right",
                            lineBreak: false,
                        }
                    );
            }

            doc.end();

            stream.on(
                "finish",
                () => {
                    resolve(
                        `/uploads/reports/${fileName}`
                    );
                }
            );

            stream.on("error", reject);
        } catch (error) {
            reject(error);
        }
    });
};